name: Build & Test

on:
  push:
    branches:
      - main
      - 'P*_*'
      - 'P*_T*_*'
  pull_request:
    branches:
      - main
      - 'P*_*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore src/ChaosOverlords.sln

      - name: Build
        run: dotnet build src/ChaosOverlords.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test src/ChaosOverlords.sln --configuration Release --no-build
